name: Turbo Action
on: [push]
jobs:
  verify-and-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Setup husky
        run: pnpm prepare
      - name: Lint code
        run: pnpm lint
      - name: Format code
        run: pnpm format
      - name: Build check
        run: pnpm build
